# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VN9Y0R4UA9U5vK_Fj1y8PIxx1EV4ex1d
"""

import streamlit as st
import geopandas as gpd
import rasterio
import numpy as np
from rasterio.mask import mask
import folium
from streamlit_folium import st_folium

st.set_page_config(page_title="Crop Monitoring Dashboard", layout="wide")

st.title("🌾 Plot Wise Crop Monitoring Dashboard")

# ---------------- LOAD DATA ---------------- #
@st.cache_data
def load_plots():
    gdf = gpd.read_file(r"F:\ndviApp\data\Rabi_plot.shp")
    gdf.columns = gdf.columns.str.lower()
    return gdf

plots = load_plots()

# ---------------- NDVI FILES ---------------- #
ndvi_files = {
    "2020": r"F:\ndviApp\data\Rabi_2020.tif",
    "2021": r"F:\ndviApp\data\Rabi_2021.tif",
    "2022": r"F:\ndviApp\data\Rabi_2022.tif",
    "2023": r"F:\ndviApp\data\Rabi_2023.tif",
    "2024": r"F:\ndviApp\data\Rabi_2024.tif"
}

# ---------------- SIDEBAR ---------------- #
st.sidebar.header("🔍 Select Year")
selected_year = st.sidebar.selectbox("Select Year", list(ndvi_files.keys()))

# ---------------- NDVI FUNCTION ---------------- #
def calculate_ndvi(plot_geom, year):

    geom = [plot_geom.__geo_interface__]
    tif_path = ndvi_files.get(year)

    try:
        with rasterio.open(tif_path) as src:

            out_image, _ = mask(src, geom, crop=True)
            data = out_image[0]

            if src.nodata is not None:
                data = data[data != src.nodata]

            data = data[(data > 0) & (data <= 1)]

            if data.size > 0:
                return float(np.mean(data))

    except Exception as e:
        st.error(f"NDVI Error: {e}")

    return None

# ---------------- MAP ---------------- #
st.subheader("📍 Click on Plot")

plots_map = plots.to_crs(epsg=4326)

center = plots_map.geometry.centroid.iloc[0]

m = folium.Map(location=[center.y, center.x], zoom_start=15, tiles=None)

# Satellite background
folium.TileLayer(
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attr="Esri",
    name="Satellite",
    overlay=False,
    control=True
).add_to(m)

# ---------------- ADD POLYGONS ---------------- #
for _, row in plots_map.iterrows():

    geom = row.geometry
    pid = row['id']
    crop_type = row['crop_type']

    # ✅ Recalculate NDVI EVERY TIME based on selected year
    ndvi_val = calculate_ndvi(geom, selected_year)

    if ndvi_val is None:
        health = "No Data"
    elif ndvi_val < 0.2:
        health = "Poor"
    elif ndvi_val < 0.4:
        health = "Moderate"
    else:
        health = "Healthy"

    popup_text = f"""
    <b>Plot ID:</b> {pid}<br>
    <b>Crop:</b> {crop_type}<br>
    <b>Year:</b> {selected_year}<br>
    <b>NDVI:</b> {round(ndvi_val,3) if ndvi_val is not None else 'No Data'}<br>
    <b>Health:</b> {health}
    """

    # ✅ SAME boundary style for all plots (no color change)
    folium.GeoJson(
        geom,
        style_function=lambda x: {
            "fillColor": "transparent",   # no fill color
            "color": "cyan",              # same boundary
            "weight": 2,
            "fillOpacity": 0
        },
        popup=folium.Popup(popup_text, max_width=250)
    ).add_to(m)

# Layer control
folium.LayerControl().add_to(m)

# Show map
st_folium(m, width=1000, height=600)